# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Gage Neumaier
email: gage.neumaier@gmail.com
description: Aspiring Help Desk Technician
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://WillieJay5.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  WillieJay5


#adding Author Information
Author:
  name: Gage Neumaier
  picture: /assets/img/me.jpg
  social:
    email: gage.neumaier@gmail.com
    github: WillieJay5
    linkedin: gage-neumaier-239ab21a5
  about: |
    I’m Gage Neumaier, an aspiring IT Help Desk Technician with a strong foundation in technical support, cybersecurity, and system administration. Through a hands-on cybersecurity bootcamp and self-guided projects, I’ve developed practical skills in Windows and Linux environments, Active Directory, network troubleshooting, and Microsoft 365 support. I’m passionate about solving technical problems, supporting end users, and continuing to grow in the IT field. With a client-first mindset, strong communication skills, and a drive to learn, I’m eager to jumpstart my IT career and bring my knowledge and dedication to a help desk role and beyond.

#Menu settings
menu:
  - title: Home
    url:   /
  - title: About
    url:   /about/
  - title: Guides
    url:   /guides/
  - title: Projects
    url:   /projects/
  - title: Resume
    url:   /resume/

# Build settings
theme: jekyll-theme-hydejack

#Project settings
collections:
  projects:
    permalink: /projects/:path/
    output:    true
  guides:
    # Make sure the permalink path is different!
    permalink:         /guides/:path/
    output:            true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
