name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Make sure this is your actual default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures Jekyll plugins that rely on git history work properly

      - name: Install dependencies (including Ruby)
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential zlib1g-dev
          
          # Set up gem installation directory in user space (fixes permission issues)
          echo 'export GEM_HOME=$HOME/.gem' >> $HOME/.bashrc
          echo 'export PATH=$HOME/.gem/bin:$PATH' >> $HOME/.bashrc
          source $HOME/.bashrc

          ruby -v  # Check Ruby version

      - name: Install Bundler and Dependencies
        run: |
          export GEM_HOME=$HOME/.gem
          export PATH=$HOME/.gem/bin:$PATH

          gem install bundler --user-install
          bundle config set --local path 'vendor/bundle'  # Ensure gems install locally
          bundle install --jobs 4 --retry 3  # Install dependencies with parallel jobs for speed

      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build Jekyll site
        run: |
          export GEM_HOME=$HOME/.gem
          export PATH=$HOME/.gem/bin:$PATH
          bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
